spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/movies?autoReconnect=true&useSSL=false
    username: root
    password: password